name: pytest

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -U pdm torch pytest pytest-cov pytest-sugar
        pdm install --no-lock
        python -m pip install -e .
    - name: Analysing the code with pytest
      run: |
        pytest -vvvv --cov=BiLLM tests/
